sudo: required
services:
  - docker

before_install:
  - docker build -t adityakarnik/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run adityakarnik/react-test npm test -- --coverage

after_success:
  - docker build -t adityakarnik/multi-client ./client
  - docker build -t adityakarnik/multi-nginx ./nginx
  - docker build -t adityakarnik/multi-server ./server
  - docker build -t adityakarnik/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push adityakarnik/multi-client
  - docker push adityakarnik/milti-nginx 
  - docker push adityakarnik/multi-server
  - docker push adityakarnik/multi-worker
  