sudo: required
services:
  - docker

before_install:
  - docker build -t adityakarnik/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run adityakarnik/react-test npm test -- --coverage

after_success:
  - docker build -t adityakarnik/multi-client ./client
  - docker build -t adityakarnik/multi-nginx ./nginx
  - docker build -t adityakarnik/multi-server ./server
  - docker build -t adityakarnik/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push adityakarnik/multi-client
  - docker push adityakarnik/multi-nginx 
  - docker push adityakarnik/multi-server
  - docker push adityakarnik/multi-worker
  

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-us-east-1-018794499249
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY